const path = {
  home: "/",
  login: "/login",
  logout: "/logout",
  register: "/register",
  search: "/search",
  orders: "/orders",
  users: "/users",
  usersNew: "/users/new",
  usersDetail: "/user/detail/:id",
  products: "/products",
  smartPhone: "/smartPhone",
  smartPhoneDetail: "/smartPhone/detail/:nameId",
  smartPhoneUpdate: "/smartPhone/detail/update/:nameId",
  smartPhoneNew: "/smartPhoneNew",
  laptop: "/laptop",
  laptopDetail: "/laptop/detail/:nameId",
  laptopUpdate: "/laptop/detail/update/:nameId",
  laptopNew: "/laptopNew",
  categories: "/categories",
  category: "/category/detail",
  categoryNew: "/category/new",
  brand: "/brand",
  brandDetail: "/brand/detail/:id",
  brandNew: "/brand/new",
  ram: "/ram",
  ramDetail: "/ram/detail/:nameId",
  ramNew: "/ram/new",
  rom: "/rom",
  romDetail: "/rom/detail/:nameId",
  romNew: "/rom/new",
  processor: "/processor",
  processorDetail: "/processor/detail/:nameId",
  processorNew: "/processor/new",
  cardGrap: "/cardGraphic",
  cardGrapDetail: "/cardGraphic/detail/:nameId",
  cardGrapNew: "/cardGraphic/new",
  tablet: "/tablet",
  tabletDetail: "/tablet/detail/:nameId",
  tabletUpdate: "/tablet/detail/update/:nameId",
  tabletNew: "/tabletNew",
  smartWatch: "/smartWatch",
  smartWatchDetail: "/smartWatch/detail/:nameId",
  smartWatchUpdate: "/smartWatch/detail/update/:nameId",
  smartWatchNew: "/smartWatchNew",
  mouse: "/mouse",
  mouseDetail: "/mouse/detail/:nameId",
  mouseUpdate: "/mouse/detail/update/:nameId",
  mouseNew: "/mouseNew",
  loudSpeaker: "/loudSpeaker",
  loudSpeakerDetail: "/loudSpeaker/detail/:nameId",
  loudSpeakerUpdate: "/loudSpeaker/detail/update/:nameId",
  loudSpeakerNew: "/loudSpeakerNew",
  keyboard: "/keyboard",
  keyboardDetail: "/keyboard/detail/:nameId",
  keyboardUpdate: "/keyboard/detail/update/:nameId",
  keyboardNew: "/keyboardNew",
  /////////
  monitor: "/monitor",
  monitorDetail: "/monitor/detail/:nameId",
  monitorUpdate: "/monitor/detail/update/:nameId",
  monitorNew: "/monitorNew",

  microPhone: "/microPhone",
  microPhoneDetail: "/microPhone/detail/:nameId",
  microPhoneUpdate: "/microPhone/detail/update/:nameId",
  microPhoneNew: "/microPhoneNew",

  mainBoard: "/mainBoard",
  mainBoardDetail: "/mainBoard/detail/:nameId",
  mainBoardUpdate: "/mainBoard/detail/update/:nameId",
  mainBoardNew: "/mainBoardNew",

  computerPower: "/computerPower",
  computerPowerDetail: "/computerPower/detail/:nameId",
  computerPowerUpdate: "/computerPower/detail/update/:nameId",
  computerPowerNew: "/computerPowerNew",

  backupCharger: "/backupCharger",
  backupChargerDetail: "/backupCharger/detail/:nameId",
  backupChargerUpdate: "/backupCharger/detail/update/:nameId",
  backupChargerNew: "/backupChargerNew",

  adapter: "/adapter",
  adapterDetail: "/adapter/detail/:nameId",
  adapterUpdate: "/adapter/detail/update/:nameId",
  adapterNew: "/adapterNew",

  feedback: "/feedback",
  feedbackDetail: "/feedback/:id",
} as const;

export default path;

