const path = {
  home: "/",
  login: "/login",
  logout: "/logout",
  register: "/register",
  orders: "/orders",
  users: "/users",
  usersNew: "/users/new",
  usersDetail: "/user/detail",
  products: "/products",
  smartPhone: "/smartPhone",
  smartPhoneDetail: "/smartPhone/detail/:nameId",
  smartPhoneUpdate: "/smartPhone/detail/update/:nameId",
  smartPhoneNew: "/smartPhoneNew",
  laptop: "/laptop",
  laptopDetail: "/laptop/detail/:nameId",
  laptopUpdate: "/laptop/detail/update/:nameId",
  laptopNew: "/laptopNew",
  categories: "/categories",
  category: "/category/detail",
  categoryNew: "/category/new",
  brand: "/brand",
  brandDetail: "/brand/detail",
  brandNew: "/brand/new",
} as const;

export default path;
