import type { RegisterOptions, UseFormGetValues } from "react-hook-form";
import * as yup from "yup";

type Rules = {
  [key in "email" | "password" | "confirm_password"]?: RegisterOptions;
};

function testPriceMinMax(this: yup.TestContext<yup.AnyObject>) {
  const parent = this.parent?.lstProductTypeAndPrice;

  if (parent[0]?.salePrice !== "" && parent[0]?.price !== "") {
    return Number(parent[0]?.price) >= Number(parent[0]?.salePrice);
  }
  if (parent[1]?.salePrice !== "" && parent[1]?.price !== "") {
    return Number(parent[1]?.price) >= Number(parent[1]?.salePrice);
  }
  if (parent[2]?.salePrice !== "" && parent[2]?.price !== "") {
    return Number(parent[2]?.price) >= Number(parent[2]?.salePrice);
  }
  if (parent[3]?.salePrice !== "" && parent[3]?.price !== "") {
    return Number(parent[3]?.price) >= Number(parent[3]?.salePrice);
  }

  return (
    parent[0]?.salePrice !== "" || parent[0]?.price !== ""
    // price1 !== "" ||
    // price2 !== "" ||
    // price3 ||
    // salePrice1 !== "" ||
    // salePrice2 !== "" ||
    // salePrice3 !== ""
  );
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const getRules = (getValues?: UseFormGetValues<any>): Rules => ({
  email: {
    required: {
      value: true,
      message: "Email là bắt buộc",
    },
    pattern: {
      value: /^\S+@\S+\.\S+$/,
      message: "Email không đúng định dạng",
    },
    maxLength: {
      value: 160,
      message: "Độ dài từ 5 - 160 ký tự",
    },
    minLength: {
      value: 5,
      message: "Độ dài từ 5 - 160 ký tự",
    },
  },
  password: {
    required: {
      value: true,
      message: "Password là bắt buộc",
    },
    maxLength: {
      value: 160,
      message: "Độ dài từ 6 - 160 ký tự",
    },
    minLength: {
      value: 6,
      message: "Độ dài từ 6 - 160 ký tự",
    },
  },
  confirm_password: {
    required: {
      value: true,
      message: "Nhập lại password là bắt buộc",
    },
    maxLength: {
      value: 160,
      message: "Độ dài từ 6 - 160 ký tự",
    },
    minLength: {
      value: 6,
      message: "Độ dài từ 6 - 160 ký tự",
    },
    validate:
      typeof getValues === "function"
        ? (value) =>
            value === getValues("password") || "Nhập lại password không khớp"
        : undefined,
  },
});

const handleConfirmPasswordYup = (refString: string) => {
  return yup
    .string()
    .required("Nhập lại password là bắt buộc")
    .min(6, "Độ dài từ 6 - 160 ký tự")
    .max(160, "Độ dài từ 6 - 160 ký tự")
    .oneOf([yup.ref(refString)], "Nhập lại password không khớp");
};

export const schema = yup.object({
  phone: yup
    .string()
    .required("Số điện thoại là bắt buộc")
    .min(5, "Độ dài từ 5 - 160 ký tự")
    .max(160, "Độ dài từ 5 - 160 ký tự"),
  password: yup
    .string()
    .required("Password là bắt buộc")
    .min(6, "Độ dài từ 6 - 160 ký tự")
    .max(160, "Độ dài từ 6 - 160 ký tự"),
  confirm_password: handleConfirmPasswordYup("password"),
});

export const userSchema = yup.object({
  name: yup.string().max(160, "Độ dài tối đa là 160 ký tự"),
  avatar: yup.string().max(1000, "Độ dài tối đa là 1000 ký tự"),
  password: schema.fields["password"],
  new_password: schema.fields["password"],
  confirm_password: handleConfirmPasswordYup("new_password"),
});

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const schemaAddUser = yup.object({
  gender: yup.number(),
  phoneNumber: yup
    .string()
    .required("Số điện thoại là bắt buộc")
    .min(10, "Độ dài từ 10 chữ số")
    .matches(
      /(84|0[3|5|7|8|9])+([0-9]{8})\b/g,
      "Số điện thoại không đúng định dạng",
    ),
  fullName: yup.string().required("Họ tên là bắt buộc"),
  email: yup
    .string()
    .required("Email là bắt buộc")
    .email("Email không đúng định dạng")
    .min(5, "Độ dài từ 5 - 160 ký tự")
    .max(160, "Độ dài từ 5 - 160 ký tự"),
  password: yup
    .string()
    .min(6, "Độ dài từ 6 - 160 ký tự")
    .max(160, "Độ dài từ 6 - 160 ký tự"),
  address: yup.string(),
  imageUrl: yup.string(),
});

export const schemaProductSmartPhone = yup.object({
  brand: yup.string().required("Trường này là bắt buộc"),
  category: yup.string(),
  characteristic: yup.string().required("Trường này là bắt buộc"),
  name: yup.string().required("Trường này là bắt buộc"),
  description: yup.string().required("Trường này là bắt buộc"),
  design: yup.string().required("Trường này là bắt buộc"),
  dimension: yup.string().required("Trường này là bắt buộc"),
  mass: yup.string().required("Trường này là bắt buộc"),
  accessories: yup.string().required("Trường này là bắt buộc"),
  productStatus: yup.number(),
  ram: yup.string(),
  storageCapacity: yup.string(),
  launchTime: yup
    .number()
    .required("Năm là trường bắt buộc")
    .integer("Năm phải là số nguyên")
    .max(new Date().getFullYear(), "Năm không được lớn hơn năm hiện tại"),
  color: yup.string(),
  monitor: yup.string().required("Trường này là bắt buộc"),
  operatingSystem: yup.string().required("Trường này là bắt buộc"),
  frontCamera: yup.string().required("Trường này là bắt buộc"),
  rearCamera: yup.string().required("Trường này là bắt buộc"),
  chip: yup.string().required("Trường này là bắt buộc"),
  quantity: yup.string(),
  depotId: yup.string(),
  sim: yup.string().required("Trường này là bắt buộc"),
  battery: yup.string().required("Trường này là bắt buộc"),
  charging: yup.string().required("Trường này là bắt buộc"),
  networkSupport: yup.string().required("Trường này là bắt buộc"),
  lstProductTypeAndPrice: yup.array().required("Trường này là bắt buộc"),
  files: yup.array(),
  "lstProductTypeAndPrice.0.ram": yup.string(),
  "lstProductTypeAndPrice.1.ram": yup.string(),
  "lstProductTypeAndPrice.2.ram": yup.string(),
  "lstProductTypeAndPrice.3.ram": yup.string(),
  "lstProductTypeAndPrice.4.ram": yup.string(),
  "lstProductTypeAndPrice.0.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.1.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.2.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.3.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.4.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.0.color": yup.string(),
  "lstProductTypeAndPrice.1.color": yup.string(),
  "lstProductTypeAndPrice.2.color": yup.string(),
  "lstProductTypeAndPrice.3.color": yup.string(),
  "lstProductTypeAndPrice.4.color": yup.string(),
  "lstProductTypeAndPrice.0.price": yup.string().test({
    name: "price-not-allowed",
    message: "Giá khuyến mãi phải nhỏ hơn giá gốc",
    test: testPriceMinMax,
  }),
  "lstProductTypeAndPrice.1.price": yup.string().test({
    name: "price-not-allowed",
    message: "Giá khuyến mãi phải nhỏ hơn giá gốc",
    test: testPriceMinMax,
  }),
  "lstProductTypeAndPrice.2.price": yup.string().test({
    name: "price-not-allowed",
    message: "Giá khuyến mãi phải nhỏ hơn giá gốc",
    test: testPriceMinMax,
  }),
  "lstProductTypeAndPrice.3.price": yup.string().test({
    name: "price-not-allowed",
    message: "Giá khuyến mãi phải nhỏ hơn giá gốc",
    test: testPriceMinMax,
  }),
  "lstProductTypeAndPrice.4.price": yup.string().test({
    name: "price-not-allowed",
    message: "Giá khuyến mãi phải nhỏ hơn giá gốc",
    test: testPriceMinMax,
  }),
  "lstProductTypeAndPrice.0.salePrice": yup.string().test({
    name: "price-not-allowed",
    message: "Giá khuyến mãi phải nhỏ hơn giá gốc",
    test: testPriceMinMax,
  }),
  "lstProductTypeAndPrice.1.salePrice": yup.string().test({
    name: "price-not-allowed",
    message: "Giá khuyến mãi phải nhỏ hơn giá gốc",
    test: testPriceMinMax,
  }),
  "lstProductTypeAndPrice.2.salePrice": yup.string().test({
    name: "price-not-allowed",
    message: "Giá khuyến mãi phải nhỏ hơn giá gốc",
    test: testPriceMinMax,
  }),
  "lstProductTypeAndPrice.3.salePrice": yup.string().test({
    name: "price-not-allowed",
    message: "Giá khuyến mãi phải nhỏ hơn giá gốc",
    test: testPriceMinMax,
  }),
  "lstProductTypeAndPrice.4.salePrice": yup.string().test({
    name: "price-not-allowed",
    message: "Giá khuyến mãi phải nhỏ hơn giá gốc",
    test: testPriceMinMax,
  }),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaProductSmartWatch = yup.object({
  brand: yup.string(),
  characteristic: yup.string(),
  name: yup.string(),
  description: yup.string(),
  design: yup.string(),
  dimension: yup.string(),
  mass: yup.string(),
  launchTime: yup.string(),
  accessories: yup.string(),
  productStatus: yup.number(),
  ram: yup.string(),
  storageCapacity: yup.string(),
  color: yup.string(),
  price: yup.string(),
  salePrice: yup.string(),
  monitor: yup.string(),
  frontCamera: yup.string(),
  rearCamera: yup.string(),
  chip: yup.string(),
  quantity: yup.string(),
  depotId: yup.string(),
  sim: yup.string(),
  battery: yup.string(),
  charging: yup.string(),
  networkSupport: yup.string(),
  cpu: yup.string(),
  connectToOs: yup.string(),
  internalMemory: yup.string(),
  connector: yup.string(),
  health: yup.string(),
  lstProductTypeAndPrice: yup.array(),
  files: yup.array(),
  imageUrl: yup.array(),
  "lstProductTypeAndPrice.0.ram": yup.string(),
  "lstProductTypeAndPrice.1.ram": yup.string(),
  "lstProductTypeAndPrice.2.ram": yup.string(),
  "lstProductTypeAndPrice.3.ram": yup.string(),
  "lstProductTypeAndPrice.4.ram": yup.string(),
  "lstProductTypeAndPrice.0.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.1.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.2.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.3.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.4.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.0.color": yup.string(),
  "lstProductTypeAndPrice.1.color": yup.string(),
  "lstProductTypeAndPrice.2.color": yup.string(),
  "lstProductTypeAndPrice.3.color": yup.string(),
  "lstProductTypeAndPrice.4.color": yup.string(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaProductRam = yup.object({
  brand: yup.string(),
  name: yup.string(),
  description: yup.string(),
  design: yup.string(),
  characteristic: yup.string(),
  dimension: yup.string(),
  mass: yup.string(),
  launchTime: yup.string(),
  accessories: yup.string(),
  productStatus: yup.number(),
  price: yup.string(),
  salePrice: yup.string(),
  storageCapacity: yup.string(),
  monitor: yup.string(),
  lstProductTypeAndPrice: yup.array(),
  quantity: yup.string(),
  depotId: yup.string(),
  ramFor: yup.boolean(),
  model: yup.string(),
  ramType: yup.string(),
  romType: yup.string(),
  connect: yup.string(),
  readingSpeed: yup.string(),
  writingSpeed: yup.string(),
  capacity: yup.string(),
  bus: yup.number(),
  latency: yup.string(),
  voltage: yup.string(),
  led: yup.string(),
  ramTechnology: yup.string(),
  imageUrl: yup.array(),
  cpuFor: yup.boolean(),
  generation: yup.string(),
  generationName: yup.string(),
  socket: yup.string(),
  multiplier: yup.string(),
  numberOfStreams: yup.string(),
  cpuSpeed: yup.string(),
  maxSpeed: yup.string(),
  caching: yup.string(),
  memoryCapacity: yup.string(),
  graphicsEngine: yup.string(),
  standardBus: yup.string(),
  memory: yup.string(),
  memorySpeed: yup.string(),
  engineClock: yup.string(),
  outputPort: yup.string(),
  powerCapacity: yup.string(),
  maximumResolution: yup.string(),
  files: yup.array(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaProductMouse = yup.object({
  name: yup.string(),
  description: yup.string(),
  launchTime: yup.string(),
  characteristic: yup.string(),
  brand: yup.string(),
  accessories: yup.string(),
  productStatus: yup.number(),
  price: yup.string(),
  salePrice: yup.string(),
  mouseType: yup.boolean(),
  depotId: yup.string(),
  mass: yup.string(),
  dimension: yup.string(),
  compatible: yup.string(),
  resolution: yup.string(),
  connector: yup.string(),
  led: yup.string(),
  softwareSupport: yup.string(),
  batteryType: yup.string(),
  time: yup.string(),
  chargingPort: yup.string(),
  lstProductTypeAndPrice: yup.array(),
  files: yup.array(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaProductLoudSpeaker = yup.object({
  brand: yup.string(),
  characteristic: yup.string(),
  name: yup.string(),
  description: yup.string(),
  design: yup.string(),
  depotId: yup.string(),
  dimension: yup.string(),
  mass: yup.string(),
  launchTime: yup.string(),
  accessories: yup.string(),
  productStatus: yup.number(),
  price: yup.string(),
  salePrice: yup.string(),
  loudspeakerType: yup.boolean(),
  totalCapacity: yup.string(),
  time: yup.string(),
  connection: yup.string(),
  utilities: yup.string(),
  control: yup.string(),
  lstProductTypeAndPrice: yup.array(),
  files: yup.array(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaProductKeyboard = yup.object({
  depotId: yup.string(),
  name: yup.string(),
  brand: yup.string(),
  description: yup.string(),
  launchTime: yup.string(),
  characteristic: yup.string(),
  accessories: yup.string(),
  productStatus: yup.number(),
  ram: yup.string(),
  storageCapacity: yup.string(),
  color: yup.string(),
  price: yup.string(),
  mass: yup.string(),
  dimension: yup.string(),
  salePrice: yup.string(),
  keyboardType: yup.boolean(),
  compatible: yup.string(),
  connector: yup.string(),
  led: yup.string(),
  numberOfKeys: yup.string(),
  keycapsMaterial: yup.string(),
  specialKeys: yup.string(),
  softwareSupport: yup.string(),
  lstProductTypeAndPrice: yup.array(),
  files: yup.array(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaLaptop = yup.object({
  brand: yup.string().required("Trường này là bắt buộc"),
  characteristic: yup.string().required("Trường này là bắt buộc"),
  name: yup.string().required("Trường này là bắt buộc"),
  description: yup.string(),
  design: yup.string(),
  dimension: yup.string(),
  mass: yup.string(),
  launchTime: yup.string(),
  accessories: yup.string(),
  depotId: yup.string(),
  productStatus: yup.number(),
  ram: yup.string(),
  storageCapacity: yup.string(),
  color: yup.string(),
  price: yup.string(),
  salePrice: yup.string(),
  monitor: yup.string(),
  operatingSystem: yup.string(),
  lstProductTypeAndPrice: yup.array().required("Trường này là bắt buộc"),
  gateway: yup.string(),
  special: yup.string(),
  maximumRam: yup.string(),
  maximumRom: yup.string(),
  processor: yup.string(),
  ramId: yup.string().required("Trường này là bắt buộc"),
  romId: yup.string().required("Trường này là bắt buộc"),
  graphicsCard: yup.string().required("Trường này là bắt buộc"),
  files: yup.array(),
  imageUrl: yup.array(),
  "lstProductTypeAndPrice.0.ram": yup.string(),
  "lstProductTypeAndPrice.1.ram": yup.string(),
  "lstProductTypeAndPrice.2.ram": yup.string(),
  "lstProductTypeAndPrice.3.ram": yup.string(),
  "lstProductTypeAndPrice.4.ram": yup.string(),
  "lstProductTypeAndPrice.0.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.1.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.2.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.3.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.4.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.0.color": yup.string(),
  "lstProductTypeAndPrice.1.color": yup.string(),
  "lstProductTypeAndPrice.2.color": yup.string(),
  "lstProductTypeAndPrice.3.color": yup.string(),
  "lstProductTypeAndPrice.4.color": yup.string(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaBrand = yup.object({
  name: yup.string().required("Tên nhãn hiệu là bắt buộc"),
  address: yup.string(),
  imageUrl: yup.string(),
  slug: yup.string(),
});

export const schemaCategory = yup.object({
  name: yup.string().required("Tên danh mục là bắt buộc"),
  slug: yup.string(),
  parentCategoryId: yup.number(),
});

export const schemaSmartWatch = yup.object({
  loaiSp: yup.string().required("Loại sản phẩm là bắt buộc"),
  sex: yup.string().required("Giới tính là bắt buộc"),
  face: yup.string(),
  characteristic: yup.string(),
  pin: yup.string(),
  healcare: yup.string(),
  dimension: yup.string(),
  mass: yup.string(),
  name: yup.string().required("Tên sp là bắt buộc"),
  model: yup.string().required("Hãng sx là bắt buộc"),
  price: yup.string().required("Giá sản phẩm là bắt buộc"),
  sale: yup.string(),
  mota: yup.string().required("Mô tả là bắt buộc"),
  upload: yup.string().required(" là bắt buộc"),
  "lstProductTypeAndPrice.0.ram": yup.string(),
  "lstProductTypeAndPrice.1.ram": yup.string(),
  "lstProductTypeAndPrice.2.ram": yup.string(),
  "lstProductTypeAndPrice.3.ram": yup.string(),
  "lstProductTypeAndPrice.4.ram": yup.string(),
  "lstProductTypeAndPrice.0.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.1.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.2.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.3.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.4.storageCapacity": yup.string(),
  "lstProductTypeAndPrice.0.color": yup.string(),
  "lstProductTypeAndPrice.1.color": yup.string(),
  "lstProductTypeAndPrice.2.color": yup.string(),
  "lstProductTypeAndPrice.3.color": yup.string(),
  "lstProductTypeAndPrice.4.color": yup.string(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaAdapter = yup.object({
  brand: yup.string(),
  name: yup.string().required("Trường này là bắt buộc"),
  description: yup.string(),
  characteristic: yup.string(),
  design: yup.string(),
  dimension: yup.string(),
  mass: yup.string(),
  launchTime: yup.string(),
  accessories: yup.string(),
  depotId: yup.string(),
  productStatus: yup.number(),
  price: yup.string(),
  salePrice: yup.string(),
  lstProductTypeAndPrice: yup.array(),
  files: yup.array(),
  adapterType: yup.string(),
  model: yup.string(),
  input: yup.string(),
  output: yup.string(),
  maximumCapacity: yup.string(),
  technology: yup.string(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaMonitor = yup.object({
  brand: yup.string(),
  name: yup.string().required("Trường này là bắt buộc"),
  description: yup.string(),
  design: yup.string(),
  dimension: yup.string(),
  mass: yup.string(),
  characteristic: yup.string(),
  launchTime: yup.string(),
  accessories: yup.string(),
  depotId: yup.string(),
  productStatus: yup.number(),
  price: yup.string(),
  salePrice: yup.string(),
  lstProductTypeAndPrice: yup.array(),
  files: yup.array(),
  segmentation: yup.string(),
  displaySize: yup.string(),
  aspectRatio: yup.string(),
  resolution: yup.string(),
  panels: yup.string(),
  scanFrequency: yup.string(),
  responseTime: yup.string(),
  contract: yup.string(),
  brightness: yup.string(),
  connectors: yup.string(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaComputerPower = yup.object({
  brand: yup.string(),
  name: yup.string().required("Trường này là bắt buộc"),
  description: yup.string(),
  characteristic: yup.string(),
  design: yup.string(),
  dimension: yup.string(),
  mass: yup.string(),
  launchTime: yup.string(),
  accessories: yup.string(),
  depotId: yup.string(),
  productStatus: yup.number(),
  price: yup.string(),
  salePrice: yup.string(),
  lstProductTypeAndPrice: yup.array(),
  files: yup.array(),
  model: yup.string(),
  pfc: yup.string(),
  efficiency: yup.string(),
  modular: yup.string(),
  voltage: yup.string(),
  outputPower: yup.string(),
  powerExcursion: yup.string(),
  frequency: yup.string(),
  fan: yup.string(),
  certifications: yup.string(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaBackup = yup.object({
  brand: yup.string(),
  name: yup.string().required("Trường này là bắt buộc"),
  description: yup.string(),
  design: yup.string(),
  dimension: yup.string(),
  characteristic: yup.string(),
  mass: yup.string(),
  launchTime: yup.string(),
  accessories: yup.string(),
  depotId: yup.string(),
  productStatus: yup.number(),
  price: yup.string(),
  salePrice: yup.string(),
  lstProductTypeAndPrice: yup.array(),
  chargingPerformance: yup.string(),
  batteryCapacity: yup.string(),
  batteryChargingTime: yup.string(),
  input: yup.string(),
  output: yup.string(),
  batteryCore: yup.string(),
  technology: yup.string(),
  files: yup.array(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaMainboard = yup.object({
  brand: yup.string(),
  name: yup.string().required("Trường này là bắt buộc"),
  description: yup.string(),
  design: yup.string(),
  characteristic: yup.string(),
  dimension: yup.string(),
  mass: yup.string(),
  launchTime: yup.string(),
  accessories: yup.string(),
  depotId: yup.string(),
  productStatus: yup.number(),
  price: yup.string(),
  salePrice: yup.string(),
  lstProductTypeAndPrice: yup.array(),
  files: yup.array(),
  mainboardFor: yup.boolean(),
  model: yup.string(),
  socket: yup.string(),
  chipset: yup.string(),
  memory: yup.string(),
  graphicsCard: yup.string(),
  sound: yup.string(),
  lan: yup.string(),
  wifiBluetooth: yup.string(),
  expansionSlot: yup.string(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export const schemaMicrophone = yup.object({
  brand: yup.string(),
  name: yup.string().required("Trường này là bắt buộc"),
  description: yup.string(),
  design: yup.string(),
  characteristic: yup.string(),
  dimension: yup.string(),
  mass: yup.string(),
  launchTime: yup.string(),
  accessories: yup.string(),
  depotId: yup.string(),
  productStatus: yup.number(),
  price: yup.string(),
  salePrice: yup.string(),
  lstProductTypeAndPrice: yup.array(),
  files: yup.array(),
  microphoneType: yup.boolean(),
  compatible: yup.string(),
  jack: yup.string(),
  feature: yup.string(),
  control: yup.string(),
  "lstProductTypeAndPrice.0.price": yup.string(),
  "lstProductTypeAndPrice.1.price": yup.string(),
  "lstProductTypeAndPrice.2.price": yup.string(),
  "lstProductTypeAndPrice.3.price": yup.string(),
  "lstProductTypeAndPrice.4.price": yup.string(),
  "lstProductTypeAndPrice.0.salePrice": yup.string(),
  "lstProductTypeAndPrice.1.salePrice": yup.string(),
  "lstProductTypeAndPrice.2.salePrice": yup.string(),
  "lstProductTypeAndPrice.3.salePrice": yup.string(),
  "lstProductTypeAndPrice.4.salePrice": yup.string(),
  "lstProductTypeAndPrice.0.quantity": yup.string(),
  "lstProductTypeAndPrice.1.quantity": yup.string(),
  "lstProductTypeAndPrice.2.quantity": yup.string(),
  "lstProductTypeAndPrice.3.quantity": yup.string(),
  "lstProductTypeAndPrice.4.quantity": yup.string(),
  "lstProductTypeAndPrice.0.depot": yup.string(),
  "lstProductTypeAndPrice.1.depot": yup.string(),
  "lstProductTypeAndPrice.2.depot": yup.string(),
  "lstProductTypeAndPrice.3.depot": yup.string(),
  "lstProductTypeAndPrice.4.depot": yup.string(),
});

export type UserSchema = yup.InferType<typeof userSchema>;

export type Schema = yup.InferType<typeof schema>;

